# SPDX-PackageName: finnix-docs
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://forge.colobox.com/finnix/finnix-docs
# SPDX-FileCopyrightText: © 2023 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0
---
fail_fast: false

repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "3e8a8703264a2f4a69428a0aa4dcb512790b2c8c"  # v6.0.0
    hooks:
      - id: "check-added-large-files"
      - id: "check-case-conflict"
      - id: "check-executables-have-shebangs"
      - id: "check-xml"
      - id: "check-yaml"
        args:
          - "--unsafe"
      - id: "check-json"
      - id: "check-shebang-scripts-are-executable"
      - id: "detect-private-key"
      - id: "end-of-file-fixer"
      - id: "fix-byte-order-marker"
      - id: "check-toml"
      - id: "trailing-whitespace"

  - repo: "https://github.com/adrienverge/yamllint"
    rev: "cba56bcde1fdd01c1deb3f945e69764c291a6530"  # v1.38.0
    hooks:
      - id: "yamllint"
        args:
          - "-c"
          - ".yamllint.yml"

  - repo: "https://github.com/psf/black"
    rev: "87928e6d6761a4a6d22250e1fee5601b3998086e"  # 26.5.1
    hooks:
      - id: "black"

  - repo: "https://github.com/pycqa/flake8"
    rev: "c48217e1fc006c2dddd14df54e83b67da15de5cd"  # 7.3.0
    hooks:
      - id: "flake8"

  - repo: "https://codeberg.org/fsfe/reuse-tool"
    rev: "a1bb792acda6fd0724936b4ebbdbc8eceb9c0459"  # v6.2.0
    hooks:
      - id: "reuse-lint-file"

  - repo: "https://forge.colobox.com/rfinnie/woodpecker-shellcheck"
    rev: "aa1061cff5d2f6888ea0592f1faed65d2c14916a"  # v1.3.0
    hooks:
      - id: "woodpecker-shellcheck"
