# SPDX-PackageName: finnix-docs
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://codeberg.org/finnix/finnix-docs
# SPDX-FileCopyrightText: © 2023 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0
---
extends: "default"

rules:
  braces:
    max-spaces-inside: 1
    max-spaces-inside-empty: 0
    min-spaces-inside: 1
    min-spaces-inside-empty: 0
    level: "error"
  brackets:
    max-spaces-inside-empty: 0
    min-spaces-inside-empty: 0
    level: "error"
  colons:
    level: "error"
  commas:
    max-spaces-after: -1
    level: "error"
  comments:
    min-spaces-from-content: 1
    level: "error"
  comments-indentation:
    level: "error"
  document-start:
    level: "error"
  empty-lines:
    level: "error"
  hyphens:
    level: "error"
  indentation:
    spaces: 2
    level: "error"
  key-duplicates:
    level: "error"
  line-length:
    max: 160
    level: "error"
  new-lines:
    level: "error"
  quoted-strings:
    quote-type: "consistent"
    required: true
    level: "error"
  truthy:
    level: "error"
